### ISSUE TITLE
How severe is known issue 776516

### ISSUE THREAD

**Issue by ursqontis** [microsoft/dotnet#1060]
It is not clear to me how severe known issue [776516](https://github.com/Microsoft/dotnet/blob/master/releases/net48/KnownIssues/776516-InvalidOperationException%20in%20System_Web_ni!System.Web.Hosting.RecycleLimitMonitor%2BRecycleLimitMonitorSingleton.AlertProxyMonitors.md) is in a high-performance / high-availability productive environment. Could the problem potentially arise in any ASP.NET (MVC) application, or only if we use those proxy monitors (whatever that is?). Should we wait for the hotfix before upgrading ASP.NET applications to v4.8?

**Comment by StephenMolloy** [comment]
This issue was introduced in 4.7, so if you're already on 4.7 or later, you already have the bug. A fix for 4.8 was released in a rollup on June 18th. (See https://support.microsoft.com/en-us/help/4502560/cumulative-update-for-net-framework-june-18-2019 for the Win10 flavor of this rollup.) I believe a 4.7.2 rollup is due shortly as well.

WRT "how severe" the issue is, I believe your question is about how likely it is that you might eoncounter the issue. All ASP.Net 4.7+ applications use the code path in question by default. Even MVC apps. It is code that supports an intrinsic housekeeping function of the ASP.Net environment. You are not very likely to hit it in the majority of cases. The environmental factors that increase your risk of hitting this bug are running in an application pool that hosts multiple app domains, or that frequently updates/restarts an app. Also, if your application pool pushes the limits for private bytes usage.
