### ISSUE TITLE
Race condition in ClientWebSocket when using keep alive

### ISSUE THREAD

**Issue by qbein** [microsoft/dotnet#1063]
For ClientWebSockets using keep alive we're experiencing an intermittent race condition when sending messages using SendAsync. When the race condition occus the result is high CPU load and an unusable socket. The SendAsync call is not aborted when the provided CancellationToken is cancelled.

The only viable work around have been to dispose the socket when the issue is detected. This will abort the SendAsync call and close the connection. This is not a good permanent solution as the socket needs to be stuck in the race condition for a few minutes before we know it is in the defunct state.

I worked with Microsoft support to analyze the issue, and a potential bug was identified in System.Net. The bug is tracked with bug no. 934174, and I was told to add this issue to track the state of this bug.

**Comment by davidsh** [comment]
Since you already have worked with Product Support on this and we have an internal bug number already (934174), it would be best to close this issue here.  

Instead, please open a feedback issue here:
https://developercommunity.visualstudio.com/spaces/61/index.html

Once you open this ticket, I will be able to link the ticket with internal bug 934174. That will provide a more efficient process for bug tracking.

**Comment by qbein** [comment]
Thanks for your reply.

I've added this feedback issue:
https://developercommunity.visualstudio.com/content/problem/620090/race-condition-in-clientwebsocket-when-using-keep.html
