### ISSUE TITLE
`-r any` doesn't work.

### ISSUE THREAD

**Issue by CalinZBaenen** [microsoft/dotnet#1295]
When ever I do `dotnet public -r any --self-contained true` on my CSharp project. it provides the error
```
C:\Program Files (x86)\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(99,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'any'. [C:\Users\Administrator\Desktop\Projects\C#\langs\Janky\language\language.csproj]
```
I tried removing `--self-contained` but the issue persisted.

**Comment by CalinZBaenen** [comment]
@DanielGlick45 Nope. That's one of the reasons I was deterred form C\#.  
I'm sorry you're experiencing this issue and I hope you find a solution.

**Comment by baronfel** [comment]
Hello @CalinZBaenen - can you open this at dotnet/sdk? We can't move issues across orgs, and the team that works on the SDK doesn't have visibility into this issue here.

**Comment by baronfel** [comment]
Sorry, I meant github organizations - issues can only be moved between dotnet/runtime and dotnet/sdk, for example, not from microsoft/dotnet to dotnet/sdk.  I asked mostly because I imagined you had more context or details that you might have wanted to submit.  I'll try to repro this when I have time and open a corresponding issue on the SDK repo.

**Comment by CalinZBaenen** [comment]
> I imagined you had more context or details that you might have wanted to submit.

Nope. I posted what I wanted to post.  
With that said, I probably should have posted more since this Issue seems somewhat vague, but I wasn't real sure what else to include or what to include based on the error.

**Comment by CalinZBaenen** [comment]
Also, unrelated, but @baronfel, are þorn and eð readable (to you)? In the browser the latter character looks a little messy on the top due to pixelation.  
I want to start switching to using them anywhere except source-code.

**Comment by baronfel** [comment]
At my chosen font size those characters are fine, the second grapheme is a little cluttered but I also use a relatively small font.

**Comment by CalinZBaenen** [comment]
Alright, thank you. \:\)

**Comment by richlander** [comment]
> `dotnet public -r any --self-contained true`

`-r any` and `--self-contained` don't match as options. As designed, self-contained apps can only ever be for one runtime/RID, in large part because they contain a runtime. In a counter-factual design, we could make `any` download all the runtimes and all the hosts. I don't think anyone wants that.

This is the only way to use `any`:

```bash
 % dotnet build -r any --self-contained false -p:UseAppHost=false
% ls bin/Debug/net6.0/any 
test.deps.json		test.pdb
test.dll		test.runtimeconfig.json
```

It produces an app w/no executable.

That said, it appears that it doesn't do anything useful. I added a reference to `SkiaSharp` and didn't get what I thought was a useful result. I recall @vitek-karas telling me that `any` doesn't do anything useful. This seems to be proving the point.

What are you trying to do?

**Comment by CalinZBaenen** [comment]
@richlander I'm not sure what @DanielGlick45 was trying to do or if they figured it out, but originally I was foolishly trying to make an executable that's work on any device without having to build it for each target.

**Comment by richlander** [comment]
Sure. We support that scenario, too. It's `dotnet foo.dll`. Works fine.

**Comment by richlander** [comment]
Here's your "any app":

```bash
 % dotnet build -o app
% dotnet app/test.dll 
Hello, World!
```

That pattern will work on any OS with a .NET runtime installed.

**Comment by richlander** [comment]
Yes. It is supported and various scenarios use just that. It works A-OK for console apps and web apps. It works poorly for client apps. Knock yourself out with this pattern!

**Comment by CalinZBaenen** [comment]
Poorly for client apps because they need to be run with a command? :P    /prob-obv

**Comment by richlander** [comment]
Right. Users except the double-click EXE experience. There are ways to work around that with scripts, but it is a pain.
