### ISSUE TITLE
Support for .NET on the HarmonyOS platform

### ISSUE THREAD

**Issue by 0x5350** [microsoft/dotnet#1321]
Good day. 

Recently, Huawei announced HarmonyOS, and their full initial product line and ecosystem for the new OS and ecosystem. 

Given the large user base of Huawei devices, and their popularity in regions such as South Africa where Huawei is the most popular platform, what would be the state of support for .NET on the HarmonyOS, and the work going forward to support this new ecosystem for countless users of Huawei devices?

**Comment by svick** [comment]
As [the issue template says](https://github.com/microsoft/dotnet/blob/master/.github/ISSUE_TEMPLATE.md), issues shouldn't be created in this repository. Because of that, you should close the issue here and reopen it on the correct repo. For this issue, I think that would be [dotnet/runtime](https://github.com/dotnet/runtime/).

**Comment by 0x5350** [comment]
Good day.

My apologies. I have been quite ignorant to all the rules regarding issues, where I was meant to know better. I shall thus close this issue at once.

**Comment by mairaw** [comment]
No worries @0x5350. I also updated the template this week to make it a bit more clear and concise.
