### ISSUE TITLE
Crash log not generated when setting NoLinkerSymbols as true

### ISSUE THREAD

**Issue by Choza-rajan** [microsoft/dotnet#1329]
I am from the Syncfusion team. In the below release notes, you have provided the RHBIND error fix and suggestions for Syncfusion controls. Can you please share the below release notes related to follow-ups with us?

https://github.com/microsoft/dotnet/blob/master/releases/UWP/net-native2.2/README.md#uwp-6212-february-9th-2021

And also if we use this suggestion, the crash reported was not generated for the application. Can you please suggest any other workaround to resolve this problem?

**Comment by premiaware** [comment]
UWP 6.2.12 (February 9th, 2021)

Error code RHBIND : error RHB0002: Failed to write PDB. Fix for build failures with RHBIN error when building Xamarin and SyncFusion UWP projects. This is an opt-in fix and requires customer to setting the msbuild property NoLinkerSymbols

I use SyncFusion Component in my UWP Project and for this reason is must use the NoLinkerSymbols during compilation. If i dont't use NoLinkerSymbols the store not working with error:

Submit error : L'invio non è riuscito con uno o più codici di errore 1201. More info about the error(s) can be found

Now i have need to use AppCenter for tracking the bugs of my App, but AppCenter not trace Stack if i use NoLinkerSymbols, so it is perfectly useless

how do you solve this thing? visual studio compiles correctly even without NoLinkerSymbols, but the store does not accept the app, it is possible that there are always problems with UWP.

**Comment by EliseJoffre** [comment]
I have the same problem can you help me please ?

**Comment by premiaware** [comment]
hello if I can very gladly

have you already tried to use this new flag?

UWP 6.2.14 (June 13th, 2022)
<OutOfProcPDB>true</OutOfProcPDB>

**Comment by EliseJoffre** [comment]
In which property group can i add "OutOfProcPDB>true</OutOfProcPDB" ?

**Comment by premiaware** [comment]
this is my project sample 

` <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <Use64BitCompiler>true</Use64BitCompiler>
    <OutputPath>bin\x64\Release\</OutputPath>
    <DefineConstants>TRACE;NETFX_CORE;WINDOWS_UWP;CODE_ANALYSIS;DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <Optimize>true</Optimize>
    <NoWarn>;2008</NoWarn>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <ErrorReport>prompt</ErrorReport>
    <Prefer32Bit>false</Prefer32Bit>
    <EnableGatekeeperAnalysis>false</EnableGatekeeperAnalysis>
    <UseDotNetNativeToolchain>true</UseDotNetNativeToolchain>
    
    <SingleThreadNUTC>true</SingleThreadNUTC>
    
    <OutOfProcPDB>true</OutOfProcPDB>
    <UseDotNetNativeSharedAssemblyFrameworkPackage>false</UseDotNetNativeSharedAssemblyFrameworkPackage>
    <ShortcutGenericAnalysis>true</ShortcutGenericAnalysis>
    
    
    
  </PropertyGroup>`

**Comment by tommcdon** [comment]
@EliseJoffre If you are still blocked by the 1201 error in Partner Center, please follow the instructions at https://github.com/dotnet/core/blob/main/Documentation/ilcRepro.md and we will try to help.

**Comment by tommcdon** [comment]
Closing this issue as we will provide assistance through [dotnetnative@microsoft.com](mailto:dotnetnative@microsoft.com).
