### ISSUE TITLE
about tuple and record suggest

### ISSUE THREAD

**Issue by nczsl** [microsoft/dotnet#1331]
tuple is already a general function in c# and the current implementation is "ValueTuple"
because the new functional "record" is very similar to it, which makes it difficult for users to choose,so I suggest
Can the underlying implementation of tuples be directly replaced by "record", or can "ValueTuple" be implemented together with record
In this way, users can not pay attention to whether record or struct record  or "Tuple" or "ValueTuple" should be used

**Comment by svick** [comment]
I'm not sure I quite understand what you're asking, but I don't think it would be possible, because tuples and records don't behave the same and modifying that would be a breaking change.

For example, tuples with matching types are the same and can be assigned to each other. But records are named types, and records with different types are not the same, even if the types of their properties matched.
