### ISSUE TITLE
WebClient DownloadData not working correctly in .NET 6

### ISSUE THREAD

**Issue by qmtdlt** [microsoft/dotnet#1400]
WebClient DownloadData not working correctly in .NET 6

I've noticed that when using .NET Framework 4.8, the `WebClient`'s `DownloadData` method works correctly, but it behaves unexpectedly in .NET 6.

Steps to Reproduce:
1. Create a .NET 6 console application.
2. Use the `DownloadData` method of `WebClient` to download a file (e.g., an image).
3. Run the application and observe whether the "the response ended prematurely" error occurs.

Expected Result:
I expect that in .NET 6, the `DownloadData` method of `WebClient` should be able to download files without encountering the "the response ended prematurely" error.

Actual Result:
In .NET 6, the `DownloadData` method of `WebClient` throws the "the response ended prematurely" error, whereas it works fine in .NET Framework 4.8.

Reproducible Code:
```csharp
var url = "http://192.168.3.8/Image.png";//The URL for capturing a screenshot from the oscilloscope.
WebClient client = new WebClient();
var bytes = client.DownloadData(new Uri(url));
```

I'm encountering similar errors while using HttpClient, RestSharp, and WebClient. It seems like the server isn't sending the complete response, which results in errors like "Error while copying content to a stream."

**Comment by qmtdlt** [comment]
![image](https://github.com/microsoft/dotnet/assets/20112289/db285f01-84a3-4045-95d9-ea463eb7739f)

**Comment by qmtdlt** [comment]
![image](https://github.com/microsoft/dotnet/assets/20112289/dc4634a6-a314-4729-84c1-59c4d75c96a7)

**Comment by qmtdlt** [comment]
![image](https://github.com/microsoft/dotnet/assets/20112289/69b6b94c-e512-4275-971d-9145225727d3)

**Comment by qmtdlt** [comment]
![image](https://github.com/microsoft/dotnet/assets/20112289/398b9b37-f71b-4beb-b268-50f1ced3c7ce)

**Comment by drraghavendra** [comment]
The WebClient.DownloadData() method is not working correctly in .NET 6. This is because the WebClient class is deprecated in .NET 6 and has been replaced by the HttpClient class.

The HttpClient class is a more modern and efficient way to make HTTP requests. It supports a wider range of features than the WebClient class, including support for WebSockets, gRPC, and OAuth 2.0.

To download a file using the HttpClient class, you can use the following code:

C#
using System.Net.Http;

public async Task DownloadFile(string url, string fileName)
{
    // Create an HttpClient instance
    HttpClient client = new HttpClient();

    // Create a request
    HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, url);

    // Execute the request
    HttpResponseMessage response = await client.SendAsync(request);

    // Check the response status code
    if (response.StatusCode == HttpStatusCode.OK)
    {
        // Save the file
        Stream fileStream = await response.Content.ReadAsStreamAsync();
        File.WriteAllBytes(fileName, fileStream.ReadAllBytes());
    }
}
In the above code, the DownloadFile method takes two parameters: the URL of the file to download and the name of the file to save it to. The method first creates an HttpClient instance. Then, it creates a HttpRequestMessage object with the GET method and the specified URL. The method then executes the request and checks the response status code. If the status code is HttpStatusCode.OK, the method saves the file to the specified location.
