### ISSUE TITLE
.NET 4.7 WinRTSpellerInterop regression

### ISSUE THREAD

**Issue by elyoh** [Microsoft/dotnet#376]
Windows® 10 x64 Version 1703 (Build 15063.138)
‎.‎NET Framework 4.7 (Build 4.7.02046)

The following code is used to clear and then add a custom dictionary location to a WPF TextBox using a valid uri pointing to a valid lex file on the filesystem:

```
textbox.SpellCheck.CustomDictionaries.Clear();
textbox.SpellCheck.CustomDictionaries.Add(uri);
```

The following exception is thrown:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Documents.WinRTSpellerInterop.LoadDictionaryImpl(String lexiconFilePath)
   at System.Windows.Documents.WinRTSpellerInterop.LoadDictionary(String lexiconFilePath)
   at System.Windows.Documents.Speller.OnDictionaryUriAdded(Uri uri)
   at System.Windows.Controls.CustomDictionarySources.System.Collections.Generic.ICollection<System.Uri>.Add(Uri item)
   at System.Windows.Controls.CustomDictionarySources.System.Collections.IList.Add(Object value)
```
Several changes have been made to LoadDictionaryImpl method in WinRTSpellerInterop.cs for .NET 4.7 and it is not immediately obvious where the issue lies.

The same code continues to work without issue on .NET 4.6.2 (4.6.01586) with Windows® 10 x64 Version 1607 (Build 14393.969).  This appears to be a regression.

Another user has produced a full repo here:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/16f8b757-ce23-42c9-a503-daa748a989f3/

A workaround appears to be:
```
textbox.SpellCheck.IsEnabled = false;
textbox.SpellCheck.CustomDictionaries.Clear();
textbox.SpellCheck.IsEnabled = true;
textbox.SpellCheck.CustomDictionaries.Add(uri);
```

**Comment by vatsan-madhavan-msft** [comment]
Thanks for the issue report, @elyoh (and also thanks to the other reporter on MSDN forums). We will use this GitHub thread to track the issue, and for future discussions etc. 

We have been able to reproduce this (thanks for the clear repro code), and are currently working on a fix. 

If anyone has an immediate adverse impact esp. in your place of business or an enteprise - for e.g., you are unable to adopt Windows 10 Creators Update because of this bug - then please let us know (and if you happen to have access to Microsoft CSS, then you probably already know how to file a bug against us through that channel as well :-) )

**Comment by JesikaDG** [comment]
We had this issue in our application, whose sole purpose is spellchecking. 
We implemented the workaround too account for this update (4.7.2046) and it no longer throws an exception. 
But we are now seeing a huge performance hit (~ x1000) when adding and clearing the dictionaries.
Adding dictionaries went from 63 milliseconds before this update to 43248 milliseconds with this update. Clearing takes about the same amount of time (42925 ms) and when doing both at the same time, clear then add, it takes 92774 ms. We are adding 4 dictionaries (not owned by us) that exist on the local machine.
The texbox that we are using is not rendered and exists in a basic class, with no associated xaml.
The issue occurs in Windows 10. The code is in a dll running inside a larger application.
Is this a side effect of this bug, or are there other things that might be causing the performance issue? Is there a better way to reset the dictionaries. Should we disable the spellchecking on the control before touching the dictionaries?

**Comment by dstraede** [comment]
We have a production mobile report writing application installed in many police vehicles.  All cars were updated to 1703, and we need a fix or we will need to uninstall 1703 in every car.  Thanks

**Comment by ABQ-Dev** [comment]
@JesikaDG I think what you're referring to is addressed in a bug report on Microsoft Connect, which is listed here: [https://connect.microsoft.com/VisualStudio/feedback/details/2153484](https://connect.microsoft.com/VisualStudio/feedback/details/2153484)

That issue is separate, unfortunately, and was introduced in .NET 4.6.1.  There is a workaround attached to that report that circumvents the issue by editing a key in the Windows registry to remove a buildup of entries for non-existent temporary dictionary files from a global list.

**Comment by JesikaDG** [comment]
@ABQ-Dev, thank you for reminding me of that issue. It was something we were aware of, but did not see occur with our code, so it had fallen off the radar. 
It appears that before we implemented the workaround for this issue, the registry key did start populating.
Our current build that uses this workaround does not write to that registry key, which was true before.

**Comment by richlander** [comment]
FYI: A fix has been made and is now in the testing phase. We expect it to ship in CY 17 Q3.

**Comment by richlander** [comment]
This fix was shipped in the .NET Framework 4.7.1. Can you validate if you can still reproduce this issue if you attempt it on .NET Framework 4.7.1?

**Comment by dstraede** [comment]
Our vendor fixed the application to work around this, so we no longer have a way to test.  But thanks for the follow up ☺

David Straede
Network Administrator, Information Technology
City of Santa Barbara, Police Department
Office (805) 897-3736 | Cell (805) 689-3283 | dstraede@sbpd.com<mailto:dstraede@sbpd.com>

**Comment by ABQ-Dev** [comment]
@richlander Thanks for following up. I can confirm that this issue is resolved in .NET Framework 4.7.1.

**Comment by elyoh** [comment]
We can no longer reproduce the issue with .NET 4.7.1 installed.
