### ISSUE TITLE
dotnet test failing with csproj file on VSTS

### ISSUE THREAD

**Issue by yatesy** [Microsoft/dotnet#407]
My situation is this. I have a simple MVC dotnet core web project, which builds and is hosted on an azure webapp. In the solution I have a xUnitTest project.

I can build both solutions successfully, and publish the result ready for the release step in VSTS. I can't do the Webapp fine, but want to run the tests after the webapp has been deployed which is where I have a problem.

Trying to run dotnet through powershell on VSTS fails saying it can't find project.json which a Visual Studio 2017 project doesn't have.

When I use the 'dotnet build' release step, it tells me that the csproj is not there, which I can see from the powershell that it definately is.

I can provide me details and screen shots if needed.

**Comment by richlander** [comment]
This is very likely due to the environment being upgraded to the .NET Core 1.0 SDK. The 1.0 SDK does not support project.json, just csproj. You must use the .NET Core 1.0 Preview 2 SDK if you would like to use project.json. You can find it here: https://github.com/dotnet/core/blob/master/release-notes/download-archive.md
