### ISSUE TITLE
Project.json no longer works

### ISSUE THREAD

**Issue by olivd** [Microsoft/dotnet#411]
You created a breaking change and pushed it out as minor release.

Bring back the project.json, down with the csproj

**Comment by svick** [comment]
> You created a breaking change and pushed it out as minor release.

It was not a minor release, it was the first non-preview release of the SDK. The last version of the SDK that supported project.json was Preview 2. csproj is fully supported since SDK 1.0.

> Bring back the project.json, down with the csproj

Sorry, that's just not going to happen. If there ever was a possibility to convince Microsoft of this, we're way past that point now. Especially considering that doing it now would actually be a breaking change in released product.

Do you have any specific suggestions about how csproj could be improved?

**Comment by olivd** [comment]
Well thanks for replying. I think it's a little cheeky to say that 1.0.3 was not a production release when you flagged it as a stable long term support release. Anyway. How about making .csproj support both xml and json equivalents ?

**Comment by svick** [comment]
> I think it's a little cheeky to say that 1.0.3 was not a production release when you flagged it as a stable long term support release.

.Net Core 1.0.3 was a stable release, but that's just the runtime, it doesn't contain the project.json tools. .Net Core SDK Preview 2, which actually let you use project.json, was not a stable release. It is kind of confusing that there is a difference between the two, but that's the way it is.

> How about making .csproj support both xml and json equivalents?

Does that mean you want JSON, but not necessarily project.json? Then you might be interested in these two issues: https://github.com/Microsoft/msbuild/issues/16, https://github.com/Microsoft/msbuild/issues/613.

Though the former one was closed with:

> We’re strongly considering more concise and expressive markup languages for future build engines. For MSBuild itself, the existing tooling ecosystem (Visual Studio and third-party) is too tied down to the existing XML format. We feel that the risks involved with a change in build-specification representation outweigh the benefits.

**Comment by olivd** [comment]
Okay thanks for that
