### ISSUE TITLE
[Question] Add microphone button to record speech?

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/dotnet#416]
I want to add microphone button in my asp.net core app, and to record speech and then using the bing speech-to-text API to convert it to text. I know the implementation of the API but I don't know how to add microphone in the view and then to use the API. I want to create something similar to google keyboard microphone.

**Comment by jnm2** [comment]
@msBot1111 What research have you done on your own? I recommend Google, and when you get stuck on something specific, ask on https://stackoverflow.com/. Those environments are much better equipped to support you in these types of questions.

**Comment by richlander** [comment]
Adding a button is the easiest part of this. I have never done this before, but a few things come to mind that you'd need to do:

- Request permission to use the user's microphone.
- Start recording.
- Capture the audio stream ... I assume you'd receive this as either an array or stream of bytes.
- Prepare the audio stream to send via an HTTP API
- Send the data stream.
- Stop recording.
- Make this work in multiple browsers.

This question is well outside the scope of this repository. It's a JavaScript question not a .NET one, since these are all browser issues.
