### ISSUE TITLE
dotnet mvc project can not work with docker correctly

### ISSUE THREAD

**Issue by chenxizhang** [Microsoft/dotnet#427]
I love dotnet core, and I want to migrate some project from legacy mode to the new platform.

Use some amazing command , with nothing change , It is work fine to me, I saw the 'hello,world"
1. dotnet new mvc
2. dotnet restore
3. dotnet run

Then I want to push it to a real world, I want to use it with docker. I create a DOCKERFILE as below
![image](https://user-images.githubusercontent.com/1996954/27251780-e4514c20-5380-11e7-9686-c0ad8e6a2625.png)

then
4. dotnet publish
5. docker build -t web . 

everything looks great, although I saw one warning message with it 
![image](https://user-images.githubusercontent.com/1996954/27251827-514bbd6e-5382-11e7-828d-5e44a09c9337.png)

Finally I want to run the image, I got the error message as below

![image](https://user-images.githubusercontent.com/1996954/27251968-096c2eae-5385-11e7-8a29-4bdbd8019a21.png)

I check the appsettings.json is really exists，how to run it correctly？

Same error reproduce in my another Ubuntu Server

**Comment by richlander** [comment]
Hi. Sorry to hear that you are having troubles. I just did something similar on my machine and wasn't able to repro your issues.

Here is what I did:

```console
dotnet new mvc -o mvcapp
cd mvcapp
dotnet restore
dotnet publish -c release
[create Dockerfile per following example]
docker build -t mvcapp .
docker run -p 8000:80 -e "ASPNETCORE_URLS=http://+:80" mvcapp
```

Here is the Dockerfile I used:

```Dockerfile
FROM microsoft/dotnet
WORKDIR /app
COPY bin/release/netcoreapp1.1/publish .
ENTRYPOINT ["dotnet", "mvcapp.dll"]
```

If instead, you change the Dockerfile to use the aspnetcore image, the commandline args get simpler because the aspnetcore image sets the ASPNETCORE_URLS environment variable. This env variable tells Kestrel which external port to listen on instead of the default loopback port. This env variable is a requirement for containers since kestrel needs to listen on an external port to "get out" of the container. See in abbreviated following example (everyone else remains the same). 

```console
docker run -p 8000:80 mvcapp
```

Here is the slightly altered Dockerfile.

```Dockerfile
FROM microsoft/aspnetcore
WORKDIR /app
COPY bin/release/netcoreapp1.1/publish .
ENTRYPOINT ["dotnet", "mvcapp.dll"]
```

For those new to the the Docker "-p" argument ... it has what I found to be the opposite order of ports. It is `host port:guest port`. In the example above, Docker is being requested to map container port 80 to port 8000 on the host machine. As a result, you need to browse to http://localhost:8000 on the host machine (your dev box).

Please try again with these instructions. Does that work better?

**Comment by richlander** [comment]
Closing ... please share if this doesn't work for you.

**Comment by chenxizhang** [comment]
it's work with dotnet core 2.0 preview, thanks you @richlander
