### ISSUE TITLE
DateTime parsing.

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/dotnet#600]
Not sure if this is normal or not (tested in a solution with .NET 4.6.1 and in Visual Studio 2017 C# Interactive window):

```
> var a = DateTime.UtcNow.ToString("ffffHHMMyytssddmm");
> DateTime ts;
> bool test = DateTime.TryParseExact(a, "ffffHHMMyytssddmm", null, System.Globalization.DateTimeStyles.None, out ts);
Index was outside the bounds of the array.
  + System.DateTimeParse.MatchAbbreviatedTimeMark(ref System.__DTString, System.Globalization.DateTimeFormatInfo, ref System.DateTimeParse.TM)
  + System.DateTimeParse.ParseByFormat(ref System.__DTString, ref System.__DTString, ref System.ParsingInfo, System.Globalization.DateTimeFormatInfo, ref System.DateTimeResult)
  + System.DateTimeParse.DoStrictParse(string, string, System.Globalization.DateTimeStyles, System.Globalization.DateTimeFormatInfo, ref System.DateTimeResult)
  + System.DateTimeParse.TryParseExact(string, string, System.Globalization.DateTimeFormatInfo, System.Globalization.DateTimeStyles, out System.DateTime)
> 
```

**Comment by tarekgh** [comment]
I cannot repro this issue. could you please try to print the value of CultureInfo.CurrentCulture to know what is your culture used in this operation? if you can share the project repro this issue that would be good too.

**Comment by wstaelens** [comment]
```
Microsoft (R) Roslyn C# Compiler version 2.6.0.62329
Loading context from 'CSharpInteractive.rsp'.
Type "#help" for more information.
> var debug = System.Globalization.CultureInfo.CurrentCulture;
> debug
[nl-BE]
> 
```

I have an asp.net mvc project on .net framework 4.6.1.
I tested this in Visual Studio Pro 2017 version 15.5.3 in the C# Interactive window.

**Comment by svick** [comment]
I can reproduce the issue on .Net 4.7.1 and .Net Core 2.0. Looking at [the source code of `MatchAbbreviatedTimeMark`](https://github.com/dotnet/coreclr/blob/15e8fc1/src/mscorlib/shared/System/Globalization/DateTimeParse.cs#L3595-L3622), this will happen for any culture where the AM or PM designator is an empty string (which is the case for nl-BE).

A simplified repro is:

```c#
DateTime.TryParseExact(" ", "%t", new CultureInfo("nl-BE"), DateTimeStyles.None, out _);
```

I think the right solution would be to ensure that all cultures have non-empty AM/PM designators, especially since it means a reasonable format like `hh:mm:ss t` is ambiguous (and thus does not round-trip).

Maybe English AM/PM designators (i.e. "AM" and "PM") are reasonable defaults for such cases?

**Comment by tarekgh** [comment]
@svick is right. I am contacting Windows team to know why nl-BE has empty strings AM/PM designators. meanwhile the workaround will be, either use a different culture or overwrite the AM/PM designators on that culture. 

```C#
            CultureInfo.CurrentCulture = new CultureInfo("nl-BE");
            CultureInfo.CurrentCulture.DateTimeFormat.AMDesignator = " ";
            CultureInfo.CurrentCulture.DateTimeFormat.PMDesignator = " ";
```

**Comment by tarekgh** [comment]
This issue was moved to dotnet/coreclr#15896
