### ISSUE TITLE
LINQ: SingleOrDefault(..) can throw InvalidOperationException but it is not documented

### ISSUE THREAD

**Issue by dmitrykorolevlighting** [Microsoft/dotnet#630]
The version of ```SingleOrDefault()``` without a predicate throws ```InvalidOperationException``` when ```The input sequence contains more than one element.```.

The version with a predicate is doing the same, however it is not documented. Due to this, one can incorrectly assume that this method returns a default value not only when a sequence contains zero elements, but also when there were more that one elements that matched the condition.

**Comment by rpetrusha** [comment]
Thank you for pointing out the missing exception information in the documentation, @dmitrykorolevlighting. Documentation issues are addressed in the [dotnet/docs](https://github.com/dotnet/docs) repo. I've opened [issue #4469](https://github.com/dotnet/docs/issues/4469) to address the missing exception information.

Although you've specified the overloaded method for which exception information is missing, you haven't indicated the type. In looking at LINQ-related **SingleOrDefault** methods, it appears that the exception information for the SingleOrDefault method that takes a predicate as an argument is missing for the [Enumerable](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.singleordefault?view=netframework-4.7.1#System_Linq_Enumerable_SingleOrDefault__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Boolean__) and [ImmutableArrayExtensions](https://docs.microsoft.com/en-us/dotnet/api/system.linq.immutablearrayextensions.singleordefault?view=netcore-2.0#System_Linq_ImmutableArrayExtensions_SingleOrDefault__1_System_Collections_Immutable_ImmutableArray___0__System_Func___0_System_Boolean__) types. If you had a different **SingleOrDefault** method in mind, please let us know by commenting in the issue in the dotnet/docs repo. 
I'll also close this issue, since the missing exception information is addressed in the dotnet/docs repo.
