### ISSUE TITLE
About /clr

### ISSUE THREAD

**Issue by daodol** [microsoft/dotnet#682]
Hello, my current project must use /MT as compiled conditions, in this case, how can I get the support of the /clr option, which is very important for me, thank you very much, I don't know whether this problem is asked here, very much hope to get your help, thank you

**Comment by svick** [comment]
I take it you're talking about compiling C++/CLI code?

According to [the documentation of `/clr`](https://docs.microsoft.com/en-us/cpp/build/reference/clr-common-language-runtime-compilation), `/clr` automatically implies `/MD`. Why is that not going to work for you?

**Comment by daoqiang** [comment]
Because my project must be compiled with the /mt option，The /clr option should automatically load some binary files of some libraries. I wonder if I can load these files on my own, so that there will be no restrictions on compiler options. Is that not the case? I'm sorry I don't really know what the /clr option has done, and I hope to get your help

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
