### ISSUE TITLE
InvokeMember fails in combination with enums backed by an ushort

### ISSUE THREAD

**Issue by fvanheeswijk** [Microsoft/dotnet#698]
This reproduces with the following sample project and .NET Framework 4.7:

```
using System;
using System.Reflection;

namespace TestProject
{
    class Program
    {
        static void Main(string[] args)
        {
            var result = typeof(Convert).InvokeMember("ToInt64", BindingFlags.IgnoreCase | BindingFlags.Static | BindingFlags.Public | BindingFlags.InvokeMethod, null, null, new object[] { SomeEnum.A });
            Console.WriteLine(result);
        }
    }

    enum SomeEnum : ushort
    {
        A = 0x01,
        B = 0x02
    }
}
```

As exception we get: System.Reflection.AmbiguousMatchException: 'Ambiguous match found.'

We have found a workaround by using:

```
var convertedEnum = Convert.ChangeType(SomeEnum.A, Enum.GetUnderlyingType(typeof(SomeEnum)));
var result = typeof(Convert).InvokeMember("ToInt64", BindingFlags.IgnoreCase | BindingFlags.Static | BindingFlags.Public | BindingFlags.InvokeMethod, null, null, new object[] { convertedEnum });
```

But it still looks like this may be an issue with the .NET Framework? It does work correctly when the enum is backed by any other underlying type than `ushort`.

**Comment by AlexGhiondea** [comment]
Thanks for this report @fvanheeswijk. I believe this is by-design.

This is happening because the following two overloads on Convert are considered ambiguous
```csharp
public static long ToInt64(ushort val) { ... }
public static long ToInt64(char val) { ... }
```

Those overloads are both applicable because you are passing in an enum member and there is a conversion from that enum to both char and ushort. In addition, the runtime cannot decide if `char` is better than `ushort` in that case because there are conversions between the two types.

The workaround you are using is how I would chose to address this issue as well.

I am going to close this for now. Feel free to reactivate!
